name: ${project.artifactId}-bukkit
main: ${project.groupId}.bukkit.MinecraftBridgeBukkit
version: ${project.version}
author: xXSchrandXx
description: WSC-Minecraft-Bridge
api-version: 1.13
load: STARTUP
softdepend: [LuckPerms, SkinsRestorer]

commands:
  wscbridge:
    description: Command for WSC-Minecraft-Bridge.
