name: ${project.artifactId}-bukkit
main: ${project.groupId}.${project.artifactId}.bukkit.MinecraftBridgeBukkit
version: ${project.version}
author: xXSchrandXx
description: WSC-Minecraft-Bridge
api-version: 1.13
load: STARTUP

commands:
  wscbridge:
    description: Command for WSC-Minecraft-Bridge.
    aliases:
    - wscbridgebukkit